[toolchain]

[features]
resolution = true
skip-lint = false

[programs.testnet]
rakurai_activation = "7hSaMpkX5A3FVeKv9YVKqPit71jb5fvRKKPFGmfdND2y"
reward_distribution = "A37zgM34Q43gKAxBWQ9zSbQRRhjPqGK8jM49H7aWqNVB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/reward_distribution", "programs/rakurai_activation"]
exclude = ["programs/vote_state"]
