[toolchain]

[features]
resolution = true
skip-lint = false

[programs.testnet]
multisig = "2Q7DK4qWRAQvYNseZ3UnWLQYjZFgyRJurP7NJDvDCusF"
block_reward_distribution = "ArEru7KcVzvVzgukQnJhZE4xsAq43bjz2ZcL1C7Wq9d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/block_reward_distribution", "programs/multisig"]
exclude = ["programs/vote_state"]
