[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
block_reward_distribution = "4wyjfWEX6746eoepd37Gb6KcPpLpkJhe4CqWzerLfpCB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/block_reward_distribution"]

[scripts]
test = "cargo test"
