[features]
resolution = true
skip-lint = false

[programs.testnet]
rakurai_activation = "pmQHMpnpA534JmxEdwY3ADfwDBFmy5my3CeutHM2QTt"
reward_distribution = "A37zgM34Q43gKAxBWQ9zSbQRRhjPqGK8jM49H7aWqNVB"

[programs.localnet]
rakurai_activation = "CuvTfdaxcDbvvtACkXrW2j69YeQbWuNnwg9FefYDrSug"
reward_distribution = "CtVB7ze4Kz2iUHGrWLWY9EG5Au1erbRCMvKTWFuKv8wq"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/reward_distribution", "programs/rakurai_activation"]
exclude = ["programs/vote_state"]
