[package]
name = "rakurai_cli"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[dependencies]
solana-sdk = "=2.1.11"
solana-client = "=2.1.11"
multisig = { path = "../programs/multisig" }
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
anchor-lang = { git = "https://github.com/coral-xyz/anchor.git", rev = "8b391aa278387b6f6ce3133453619a175544631e" }
bincode = "1.3.3"
serde = "1.0.138"
serde_derive = "1.0.103"
shellexpand = "3.1.0"
serde_json = "1.0.140"

[[bin]]
name = "rakurai-multisig-cli"
path = "src/bin/multisig_cli.rs"

