[package]
description = "Solana program to distribute block rewards amongst Rakurai, validator, and stakers. Staker rewards accumulate in a collection account and are distributed post-epoch using a merkle root."
edition = "2021"
name = "reward_distribution"
version = "0.3.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "reward_distribution"

[features]
anchor-debug = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []

[dependencies]
anchor-lang = "1.2.0"
rakurai_activation = { path = "../rakurai_activation", features = ["no-entrypoint"] }
solana-program = "3.0.0"
solana-sdk-ids = "3"
solana-system-interface = { version = "3", features = ["bincode"] }
rakurai-vote-state = { path = "../vote_state" }
solana-security-txt = "1.1.1"
